export interface Country {
  code: string;
  name: string;
  nameAr: string;
  nameFr?: string;
  flag: string;
}

export const countries: Country[] = [
  { code: "AF", name: "Afghanistan", nameAr: "أفغانستان", nameFr: "Afghanistan", flag: "🇦🇫" },
  { code: "AL", name: "Albania", nameAr: "ألبانيا", nameFr: "Albanie", flag: "🇦🇱" },
  { code: "DZ", name: "Algeria", nameAr: "الجزائر", nameFr: "Algérie", flag: "🇩🇿" },
  { code: "AD", name: "Andorra", nameAr: "أندورا", nameFr: "Andorre", flag: "🇦🇩" },
  { code: "AO", name: "Angola", nameAr: "أنغولا", nameFr: "Angola", flag: "🇦🇴" },
  { code: "AG", name: "Antigua and Barbuda", nameAr: "أنتيغوا وبربودا", nameFr: "Antigua-et-Barbuda", flag: "🇦🇬" },
  { code: "AR", name: "Argentina", nameAr: "الأرجنتين", nameFr: "Argentine", flag: "🇦🇷" },
  { code: "AM", name: "Armenia", nameAr: "أرمينيا", nameFr: "Arménie", flag: "🇦🇲" },
  { code: "AU", name: "Australia", nameAr: "أستراليا", nameFr: "Australie", flag: "🇦🇺" },
  { code: "AT", name: "Austria", nameAr: "النمسا", nameFr: "Autriche", flag: "🇦🇹" },
  { code: "AZ", name: "Azerbaijan", nameAr: "أذربيجان", nameFr: "Azerbaïdjan", flag: "🇦🇿" },
  { code: "BS", name: "Bahamas", nameAr: "جزر البهاما", nameFr: "Bahamas", flag: "🇧🇸" },
  { code: "BH", name: "Bahrain", nameAr: "البحرين", nameFr: "Bahreïn", flag: "🇧🇭" },
  { code: "BD", name: "Bangladesh", nameAr: "بنغلاديش", nameFr: "Bangladesh", flag: "🇧🇩" },
  { code: "BB", name: "Barbados", nameAr: "بربادوس", nameFr: "Barbade", flag: "🇧🇧" },
  { code: "BY", name: "Belarus", nameAr: "بيلاروسيا", nameFr: "Biélorussie", flag: "🇧🇾" },
  { code: "BE", name: "Belgium", nameAr: "بلجيكا", nameFr: "Belgique", flag: "🇧🇪" },
  { code: "BZ", name: "Belize", nameAr: "بليز", nameFr: "Belize", flag: "🇧🇿" },
  { code: "BJ", name: "Benin", nameAr: "بنين", nameFr: "Bénin", flag: "🇧🇯" },
  { code: "BT", name: "Bhutan", nameAr: "بوتان", nameFr: "Bhoutan", flag: "🇧🇹" },
  { code: "BO", name: "Bolivia", nameAr: "بوليفيا", nameFr: "Bolivie", flag: "🇧🇴" },
  { code: "BA", name: "Bosnia and Herzegovina", nameAr: "البوسنة والهرسك", nameFr: "Bosnie-Herzégovine", flag: "🇧🇦" },
  { code: "BW", name: "Botswana", nameAr: "بوتسوانا", nameFr: "Botswana", flag: "🇧🇼" },
  { code: "BR", name: "Brazil", nameAr: "البرازيل", nameFr: "Brésil", flag: "🇧🇷" },
  { code: "BN", name: "Brunei", nameAr: "بروناي", nameFr: "Brunei", flag: "🇧🇳" },
  { code: "BG", name: "Bulgaria", nameAr: "بلغاريا", nameFr: "Bulgarie", flag: "🇧🇬" },
  { code: "BF", name: "Burkina Faso", nameAr: "بوركينا فاسو", nameFr: "Burkina Faso", flag: "🇧🇫" },
  { code: "BI", name: "Burundi", nameAr: "بوروندي", nameFr: "Burundi", flag: "🇧🇮" },
  { code: "CV", name: "Cabo Verde", nameAr: "كابو فيردي", nameFr: "Cap-Vert", flag: "🇨🇻" },
  { code: "KH", name: "Cambodia", nameAr: "كمبوديا", nameFr: "Cambodge", flag: "🇰🇭" },
  { code: "CM", name: "Cameroon", nameAr: "الكاميرون", nameFr: "Cameroun", flag: "🇨🇲" },
  { code: "CA", name: "Canada", nameAr: "كندا", nameFr: "Canada", flag: "🇨🇦" },
  { code: "CF", name: "Central African Republic", nameAr: "جمهورية أفريقيا الوسطى", nameFr: "République centrafricaine", flag: "🇨🇫" },
  { code: "TD", name: "Chad", nameAr: "تشاد", nameFr: "Tchad", flag: "🇹🇩" },
  { code: "CL", name: "Chile", nameAr: "تشيلي", nameFr: "Chili", flag: "🇨🇱" },
  { code: "CN", name: "China", nameAr: "الصين", nameFr: "Chine", flag: "🇨🇳" },
  { code: "CO", name: "Colombia", nameAr: "كولومبيا", nameFr: "Colombie", flag: "🇨🇴" },
  { code: "KM", name: "Comoros", nameAr: "جزر القمر", nameFr: "Comores", flag: "🇰🇲" },
  { code: "CG", name: "Congo", nameAr: "الكونغو", nameFr: "Congo", flag: "🇨🇬" },
  { code: "CR", name: "Costa Rica", nameAr: "كوستاريكا", nameFr: "Costa Rica", flag: "🇨🇷" },
  { code: "HR", name: "Croatia", nameAr: "كرواتيا", nameFr: "Croatie", flag: "🇭🇷" },
  { code: "CU", name: "Cuba", nameAr: "كوبا", nameFr: "Cuba", flag: "🇨🇺" },
  { code: "CY", name: "Cyprus", nameAr: "قبرص", nameFr: "Chypre", flag: "🇨🇾" },
  { code: "CZ", name: "Czech Republic", nameAr: "جمهورية التشيك", nameFr: "République tchèque", flag: "🇨🇿" },
  { code: "DK", name: "Denmark", nameAr: "الدنمارك", nameFr: "Danemark", flag: "🇩🇰" },
  { code: "DJ", name: "Djibouti", nameAr: "جيبوتي", nameFr: "Djibouti", flag: "🇩🇯" },
  { code: "DM", name: "Dominica", nameAr: "دومينيكا", nameFr: "Dominique", flag: "🇩🇲" },
  { code: "DO", name: "Dominican Republic", nameAr: "جمهورية الدومينيكان", nameFr: "République dominicaine", flag: "🇩🇴" },
  { code: "EC", name: "Ecuador", nameAr: "الإكوادور", nameFr: "Équateur", flag: "🇪🇨" },
  { code: "EG", name: "Egypt", nameAr: "مصر", nameFr: "Égypte", flag: "🇪🇬" },
  { code: "SV", name: "El Salvador", nameAr: "السلفادور", nameFr: "Salvador", flag: "🇸🇻" },
  { code: "GQ", name: "Equatorial Guinea", nameAr: "غينيا الاستوائية", nameFr: "Guinée équatoriale", flag: "🇬🇶" },
  { code: "ER", name: "Eritrea", nameAr: "إريتريا", nameFr: "Érythrée", flag: "🇪🇷" },
  { code: "EE", name: "Estonia", nameAr: "إستونيا", nameFr: "Estonie", flag: "🇪🇪" },
  { code: "SZ", name: "Eswatini", nameAr: "إسواتيني", nameFr: "Eswatini", flag: "🇸🇿" },
  { code: "ET", name: "Ethiopia", nameAr: "إثيوبيا", nameFr: "Éthiopie", flag: "🇪🇹" },
  { code: "FJ", name: "Fiji", nameAr: "فيجي", nameFr: "Fidji", flag: "🇫🇯" },
  { code: "FI", name: "Finland", nameAr: "فنلندا", nameFr: "Finlande", flag: "🇫🇮" },
  { code: "FR", name: "France", nameAr: "فرنسا", nameFr: "France", flag: "🇫🇷" },
  { code: "GA", name: "Gabon", nameAr: "الغابون", nameFr: "Gabon", flag: "🇬🇦" },
  { code: "GM", name: "Gambia", nameAr: "غامبيا", nameFr: "Gambie", flag: "🇬🇲" },
  { code: "GE", name: "Georgia", nameAr: "جورجيا", nameFr: "Géorgie", flag: "🇬🇪" },
  { code: "DE", name: "Germany", nameAr: "ألمانيا", nameFr: "Allemagne", flag: "🇩🇪" },
  { code: "GH", name: "Ghana", nameAr: "غانا", nameFr: "Ghana", flag: "🇬🇭" },
  { code: "GR", name: "Greece", nameAr: "اليونان", nameFr: "Grèce", flag: "🇬🇷" },
  { code: "GD", name: "Grenada", nameAr: "غرينادا", nameFr: "Grenade", flag: "🇬🇩" },
  { code: "GT", name: "Guatemala", nameAr: "غواتيمالا", nameFr: "Guatemala", flag: "🇬🇹" },
  { code: "GN", name: "Guinea", nameAr: "غينيا", nameFr: "Guinée", flag: "🇬🇳" },
  { code: "GW", name: "Guinea-Bissau", nameAr: "غينيا بيساو", nameFr: "Guinée-Bissau", flag: "🇬🇼" },
  { code: "GY", name: "Guyana", nameAr: "غيانا", nameFr: "Guyana", flag: "🇬🇾" },
  { code: "HT", name: "Haiti", nameAr: "هايتي", nameFr: "Haïti", flag: "🇭🇹" },
  { code: "HN", name: "Honduras", nameAr: "هندوراس", nameFr: "Honduras", flag: "🇭🇳" },
  { code: "HU", name: "Hungary", nameAr: "المجر", nameFr: "Hongrie", flag: "🇭🇺" },
  { code: "IS", name: "Iceland", nameAr: "آيسلندا", nameFr: "Islande", flag: "🇮🇸" },
  { code: "IN", name: "India", nameAr: "الهند", nameFr: "Inde", flag: "🇮🇳" },
  { code: "ID", name: "Indonesia", nameAr: "إندونيسيا", nameFr: "Indonésie", flag: "🇮🇩" },
  { code: "IR", name: "Iran", nameAr: "إيران", nameFr: "Iran", flag: "🇮🇷" },
  { code: "IQ", name: "Iraq", nameAr: "العراق", nameFr: "Irak", flag: "🇮🇶" },
  { code: "IE", name: "Ireland", nameAr: "أيرلندا", nameFr: "Irlande", flag: "🇮🇪" },
  { code: "IL", name: "Israel", nameAr: "إسرائيل", nameFr: "Israël", flag: "🇮🇱" },
  { code: "IT", name: "Italy", nameAr: "إيطاليا", nameFr: "Italie", flag: "🇮🇹" },
  { code: "JM", name: "Jamaica", nameAr: "جامايكا", nameFr: "Jamaïque", flag: "🇯🇲" },
  { code: "JP", name: "Japan", nameAr: "اليابان", nameFr: "Japon", flag: "🇯🇵" },
  { code: "JO", name: "Jordan", nameAr: "الأردن", nameFr: "Jordanie", flag: "🇯🇴" },
  { code: "KZ", name: "Kazakhstan", nameAr: "كازاخستان", nameFr: "Kazakhstan", flag: "🇰🇿" },
  { code: "KE", name: "Kenya", nameAr: "كينيا", nameFr: "Kenya", flag: "🇰🇪" },
  { code: "KI", name: "Kiribati", nameAr: "كيريباتي", nameFr: "Kiribati", flag: "🇰🇮" },
  { code: "KP", name: "North Korea", nameAr: "كوريا الشمالية", nameFr: "Corée du Nord", flag: "🇰🇵" },
  { code: "KR", name: "South Korea", nameAr: "كوريا الجنوبية", nameFr: "Corée du Sud", flag: "🇰🇷" },
  { code: "KW", name: "Kuwait", nameAr: "الكويت", nameFr: "Koweït", flag: "🇰🇼" },
  { code: "KG", name: "Kyrgyzstan", nameAr: "قيرغيزستان", nameFr: "Kirghizistan", flag: "🇰🇬" },
  { code: "LA", name: "Laos", nameAr: "لاوس", nameFr: "Laos", flag: "🇱🇦" },
  { code: "LV", name: "Latvia", nameAr: "لاتفيا", nameFr: "Lettonie", flag: "🇱🇻" },
  { code: "LB", name: "Lebanon", nameAr: "لبنان", nameFr: "Liban", flag: "🇱🇧" },
  { code: "LS", name: "Lesotho", nameAr: "ليسوتو", nameFr: "Lesotho", flag: "🇱🇸" },
  { code: "LR", name: "Liberia", nameAr: "ليبيريا", nameFr: "Liberia", flag: "🇱🇷" },
  { code: "LY", name: "Libya", nameAr: "ليبيا", nameFr: "Libye", flag: "🇱🇾" },
  { code: "LI", name: "Liechtenstein", nameAr: "ليختنشتاين", nameFr: "Liechtenstein", flag: "🇱🇮" },
  { code: "LT", name: "Lithuania", nameAr: "ليتوانيا", nameFr: "Lituanie", flag: "🇱🇹" },
  { code: "LU", name: "Luxembourg", nameAr: "لوكسمبورغ", nameFr: "Luxembourg", flag: "🇱🇺" },
  { code: "MG", name: "Madagascar", nameAr: "مدغشقر", nameFr: "Madagascar", flag: "🇲🇬" },
  { code: "MW", name: "Malawi", nameAr: "ملاوي", nameFr: "Malawi", flag: "🇲🇼" },
  { code: "MY", name: "Malaysia", nameAr: "ماليزيا", nameFr: "Malaisie", flag: "🇲🇾" },
  { code: "MV", name: "Maldives", nameAr: "جزر المالديف", nameFr: "Maldives", flag: "🇲🇻" },
  { code: "ML", name: "Mali", nameAr: "مالي", nameFr: "Mali", flag: "🇲🇱" },
  { code: "MT", name: "Malta", nameAr: "مالطا", nameFr: "Malte", flag: "🇲🇹" },
  { code: "MH", name: "Marshall Islands", nameAr: "جزر مارشال", nameFr: "Îles Marshall", flag: "🇲🇭" },
  { code: "MR", name: "Mauritania", nameAr: "موريتانيا", nameFr: "Mauritanie", flag: "🇲🇷" },
  { code: "MU", name: "Mauritius", nameAr: "موريشيوس", nameFr: "Maurice", flag: "🇲🇺" },
  { code: "MX", name: "Mexico", nameAr: "المكسيك", nameFr: "Mexique", flag: "🇲🇽" },
  { code: "FM", name: "Micronesia", nameAr: "ميكرونيزيا", nameFr: "Micronésie", flag: "🇫🇲" },
  { code: "MD", name: "Moldova", nameAr: "مولدوفا", nameFr: "Moldavie", flag: "🇲🇩" },
  { code: "MC", name: "Monaco", nameAr: "موناكو", nameFr: "Monaco", flag: "🇲🇨" },
  { code: "MN", name: "Mongolia", nameAr: "منغوليا", nameFr: "Mongolie", flag: "🇲🇳" },
  { code: "ME", name: "Montenegro", nameAr: "الجبل الأسود", nameFr: "Monténégro", flag: "🇲🇪" },
  { code: "MA", name: "Morocco", nameAr: "المغرب", nameFr: "Maroc", flag: "🇲🇦" },
  { code: "MZ", name: "Mozambique", nameAr: "موزمبيق", nameFr: "Mozambique", flag: "🇲🇿" },
  { code: "MM", name: "Myanmar", nameAr: "ميانمار", nameFr: "Myanmar", flag: "🇲🇲" },
  { code: "NA", name: "Namibia", nameAr: "ناميبيا", nameFr: "Namibie", flag: "🇳🇦" },
  { code: "NR", name: "Nauru", nameAr: "ناورو", nameFr: "Nauru", flag: "🇳🇷" },
  { code: "NP", name: "Nepal", nameAr: "نيبال", nameFr: "Népal", flag: "🇳🇵" },
  { code: "NL", name: "Netherlands", nameAr: "هولندا", nameFr: "Pays-Bas", flag: "🇳🇱" },
  { code: "NZ", name: "New Zealand", nameAr: "نيوزيلندا", nameFr: "Nouvelle-Zélande", flag: "🇳🇿" },
  { code: "NI", name: "Nicaragua", nameAr: "نيكاراغوا", nameFr: "Nicaragua", flag: "🇳🇮" },
  { code: "NE", name: "Niger", nameAr: "النيجر", nameFr: "Niger", flag: "🇳🇪" },
  { code: "NG", name: "Nigeria", nameAr: "نيجيريا", nameFr: "Nigeria", flag: "🇳🇬" },
  { code: "MK", name: "North Macedonia", nameAr: "مقدونيا الشمالية", nameFr: "Macédoine du Nord", flag: "🇲🇰" },
  { code: "NO", name: "Norway", nameAr: "النرويج", nameFr: "Norvège", flag: "🇳🇴" },
  { code: "OM", name: "Oman", nameAr: "عمان", nameFr: "Oman", flag: "🇴🇲" },
  { code: "PK", name: "Pakistan", nameAr: "باكستان", nameFr: "Pakistan", flag: "🇵🇰" },
  { code: "PW", name: "Palau", nameAr: "بالاو", nameFr: "Palaos", flag: "🇵🇼" },
  { code: "PS", name: "Palestine", nameAr: "فلسطين", nameFr: "Palestine", flag: "🇵🇸" },
  { code: "PA", name: "Panama", nameAr: "بنما", nameFr: "Panama", flag: "🇵🇦" },
  { code: "PG", name: "Papua New Guinea", nameAr: "بابوا غينيا الجديدة", nameFr: "Papouasie-Nouvelle-Guinée", flag: "🇵🇬" },
  { code: "PY", name: "Paraguay", nameAr: "باراغواي", nameFr: "Paraguay", flag: "🇵🇾" },
  { code: "PE", name: "Peru", nameAr: "بيرو", nameFr: "Pérou", flag: "🇵🇪" },
  { code: "PH", name: "Philippines", nameAr: "الفلبين", nameFr: "Philippines", flag: "🇵🇭" },
  { code: "PL", name: "Poland", nameAr: "بولندا", nameFr: "Pologne", flag: "🇵🇱" },
  { code: "PT", name: "Portugal", nameAr: "البرتغال", nameFr: "Portugal", flag: "🇵🇹" },
  { code: "QA", name: "Qatar", nameAr: "قطر", nameFr: "Qatar", flag: "🇶🇦" },
  { code: "RO", name: "Romania", nameAr: "رومانيا", nameFr: "Roumanie", flag: "🇷🇴" },
  { code: "RU", name: "Russia", nameAr: "روسيا", nameFr: "Russie", flag: "🇷🇺" },
  { code: "RW", name: "Rwanda", nameAr: "رواندا", nameFr: "Rwanda", flag: "🇷🇼" },
  { code: "KN", name: "Saint Kitts and Nevis", nameAr: "سانت كيتس ونيفيس", nameFr: "Saint-Kitts-et-Nevis", flag: "🇰🇳" },
  { code: "LC", name: "Saint Lucia", nameAr: "سانت لوسيا", nameFr: "Sainte-Lucie", flag: "🇱🇨" },
  { code: "VC", name: "Saint Vincent and the Grenadines", nameAr: "سانت فنسنت وجزر غرينادين", nameFr: "Saint-Vincent-et-les-Grenadines", flag: "🇻🇨" },
  { code: "WS", name: "Samoa", nameAr: "ساموا", nameFr: "Samoa", flag: "🇼🇸" },
  { code: "SM", name: "San Marino", nameAr: "سان مارينو", nameFr: "Saint-Marin", flag: "🇸🇲" },
  { code: "ST", name: "Sao Tome and Principe", nameAr: "ساو تومي وبرينسيبي", nameFr: "Sao Tomé-et-Principe", flag: "🇸🇹" },
  { code: "SA", name: "Saudi Arabia", nameAr: "المملكة العربية السعودية", nameFr: "Arabie Saoudite", flag: "🇸🇦" },
  { code: "SN", name: "Senegal", nameAr: "السنغال", nameFr: "Sénégal", flag: "🇸🇳" },
  { code: "RS", name: "Serbia", nameAr: "صربيا", nameFr: "Serbie", flag: "🇷🇸" },
  { code: "SC", name: "Seychelles", nameAr: "سيشل", nameFr: "Seychelles", flag: "🇸🇨" },
  { code: "SL", name: "Sierra Leone", nameAr: "سيراليون", nameFr: "Sierra Leone", flag: "🇸🇱" },
  { code: "SG", name: "Singapore", nameAr: "سنغافورة", nameFr: "Singapour", flag: "🇸🇬" },
  { code: "SK", name: "Slovakia", nameAr: "سلوفاكيا", nameFr: "Slovaquie", flag: "🇸🇰" },
  { code: "SI", name: "Slovenia", nameAr: "سلوفينيا", nameFr: "Slovénie", flag: "🇸🇮" },
  { code: "SB", name: "Solomon Islands", nameAr: "جزر سليمان", nameFr: "Îles Salomon", flag: "🇸🇧" },
  { code: "SO", name: "Somalia", nameAr: "الصومال", nameFr: "Somalie", flag: "🇸🇴" },
  { code: "ZA", name: "South Africa", nameAr: "جنوب أفريقيا", nameFr: "Afrique du Sud", flag: "🇿🇦" },
  { code: "SS", name: "South Sudan", nameAr: "جنوب السودان", nameFr: "Soudan du Sud", flag: "🇸🇸" },
  { code: "ES", name: "Spain", nameAr: "إسبانيا", nameFr: "Espagne", flag: "🇪🇸" },
  { code: "LK", name: "Sri Lanka", nameAr: "سريلانكا", nameFr: "Sri Lanka", flag: "🇱🇰" },
  { code: "SD", name: "Sudan", nameAr: "السودان", nameFr: "Soudan", flag: "🇸🇩" },
  { code: "SR", name: "Suriname", nameAr: "سورينام", nameFr: "Suriname", flag: "🇸🇷" },
  { code: "SE", name: "Sweden", nameAr: "السويد", nameFr: "Suède", flag: "🇸🇪" },
  { code: "CH", name: "Switzerland", nameAr: "سويسرا", nameFr: "Suisse", flag: "🇨🇭" },
  { code: "SY", name: "Syria", nameAr: "سوريا", nameFr: "Syrie", flag: "🇸🇾" },
  { code: "TW", name: "Taiwan", nameAr: "تايوان", nameFr: "Taïwan", flag: "🇹🇼" },
  { code: "TJ", name: "Tajikistan", nameAr: "طاجيكستان", nameFr: "Tadjikistan", flag: "🇹🇯" },
  { code: "TZ", name: "Tanzania", nameAr: "تنزانيا", nameFr: "Tanzanie", flag: "🇹🇿" },
  { code: "TH", name: "Thailand", nameAr: "تايلاند", nameFr: "Thaïlande", flag: "🇹🇭" },
  { code: "TL", name: "Timor-Leste", nameAr: "تيمور الشرقية", nameFr: "Timor oriental", flag: "🇹🇱" },
  { code: "TG", name: "Togo", nameAr: "توغو", nameFr: "Togo", flag: "🇹🇬" },
  { code: "TO", name: "Tonga", nameAr: "تونغا", nameFr: "Tonga", flag: "🇹🇴" },
  { code: "TT", name: "Trinidad and Tobago", nameAr: "ترينيداد وتوباغو", nameFr: "Trinité-et-Tobago", flag: "🇹🇹" },
  { code: "TN", name: "Tunisia", nameAr: "تونس", nameFr: "Tunisie", flag: "🇹🇳" },
  { code: "TR", name: "Turkey", nameAr: "تركيا", nameFr: "Turquie", flag: "🇹🇷" },
  { code: "TM", name: "Turkmenistan", nameAr: "تركمانستان", nameFr: "Turkménistan", flag: "🇹🇲" },
  { code: "TV", name: "Tuvalu", nameAr: "توفالو", nameFr: "Tuvalu", flag: "🇹🇻" },
  { code: "UG", name: "Uganda", nameAr: "أوغندا", nameFr: "Ouganda", flag: "🇺🇬" },
  { code: "UA", name: "Ukraine", nameAr: "أوكرانيا", nameFr: "Ukraine", flag: "🇺🇦" },
  { code: "AE", name: "United Arab Emirates", nameAr: "الإمارات العربية المتحدة", nameFr: "Émirats arabes unis", flag: "🇦🇪" },
  { code: "GB", name: "United Kingdom", nameAr: "المملكة المتحدة", nameFr: "Royaume-Uni", flag: "🇬🇧" },
  { code: "US", name: "United States", nameAr: "الولايات المتحدة", nameFr: "États-Unis", flag: "🇺🇸" },
  { code: "UY", name: "Uruguay", nameAr: "أوروغواي", nameFr: "Uruguay", flag: "🇺🇾" },
  { code: "UZ", name: "Uzbekistan", nameAr: "أوزبكستان", nameFr: "Ouzbékistan", flag: "🇺🇿" },
  { code: "VU", name: "Vanuatu", nameAr: "فانواتو", nameFr: "Vanuatu", flag: "🇻🇺" },
  { code: "VA", name: "Vatican City", nameAr: "الفاتيكان", nameFr: "Vatican", flag: "🇻🇦" },
  { code: "VE", name: "Venezuela", nameAr: "فنزويلا", nameFr: "Venezuela", flag: "🇻🇪" },
  { code: "VN", name: "Vietnam", nameAr: "فيتنام", nameFr: "Viêt Nam", flag: "🇻🇳" },
  { code: "YE", name: "Yemen", nameAr: "اليمن", nameFr: "Yémen", flag: "🇾🇪" },
  { code: "ZM", name: "Zambia", nameAr: "زامبيا", nameFr: "Zambie", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabwe", nameAr: "زيمبابوي", nameFr: "Zimbabwe", flag: "🇿🇼" }
];